name: CI/CD for MySQL Automation

on:
  push:
    branches:
      - main # Change if using a different branch

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Adjust Python version if needed

      - name: Install Dependencies
        working-directory: ./DBDeploymentAzure # Change to your actual directory
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Run SQL Execution Script
        working-directory: ./DBDeploymentAzure # Change to your actual directory
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python automate_script_execution.py
